spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 158004448283-dko5teq36r32prfdfq4ttu9ebpf0og49.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email